version: "3.2"

services:
  redis:
    image: "redis:alpine"
    container_name: ${PROJECT}_redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/.docker/redis/data:/var/lib/redis
      - $PWD/.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4

  database:
    image: mariadb
    container_name: ${PROJECT}_mariadb
    command: mysqld --innodb-flush-method=O_DSYNC --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROJECT}
      MYSQL_DATABASE_TEST: ${PROJECT}_test
      MYSQL_USER: ${PROJECT}
      MYSQL_PASSWORD: ${PROJECT}    
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      - ./docker/mariadb/conf:/etc/mysql/conf.d
      - ./docker/mariadb/dump:/var/backups


  mercure:
    image: dunglas/mercure
    container_name: ${PROJECT}_mercure
    environment:
      # You should definitely change all these values in production
      - JWT_KEY=!ChangeMe! # You have to change MERCURE_JWT_TOKEN in api/.env when you change this. You can put the old value of MERCURE_JWT_TOKEN into the debugger on https://jwt.io/ and put the new value of JWT_KEY in the "secret" field to obtain the new encoded value for MERCURE_JWT_TOKEN
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
    ports:
      - "1337:80"

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  db_data:
  caddy_data:
  caddy_config:
