# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        system_loader:
            flysystem:
                filesystem_service: upload.storage
    data_loader: system_loader

    resolvers:
        default:
            flysystem:
                filesystem_service: upload.storage
                root_url:           '%env(SCHEME)%://%env(HOST)%/upload'
                cache_prefix:       cache
                visibility:         public

    filter_sets:
        cache: ~
        thumb:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [100, 100], mode: outbound }