# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        upload_loader:
            flysystem:
                filesystem_service: upload.storage
        brand_loader:
            flysystem:
                filesystem_service: brand.storage

    # default loader
    data_loader: upload_loader

    resolvers:
        default:
            flysystem:
                filesystem_service: upload.storage
                root_url:           '%env(SCHEME)%://%env(HOST)%/upload'
                cache_prefix:       cache
                visibility:         public
        brand:
            flysystem:
                filesystem_service: brand.storage
                root_url:           '%env(SCHEME)%://%env(HOST)%/media/brand'
                cache_prefix:       cache
                visibility:         public

    filter_sets:
        cache: ~
        thumb:
            quality: 75
            filters:
                auto_rotate: ~
                thumbnail: { size: [100, 100], mode: outbound }
        brand_thumb:
            data_loader: brand_loader
            quality: 75
            filters:
                relative_resize: { heighten: 100 }